images:
  image:
    repository: traefik
    tag: 3.5.1
consts:
  npm_container_name: traefik
  data_path: /data
  notes_body: |
    ## Default Username and Password

    The First time you log into the Nginx Proxy Manager UI, use the following credentials.
    You will be prompted to change them on first login.

    - Username: `admin@example.com`
    - Password: `changeme`
