#set resource limits
resources:
  limits:
    cpus: 2.0
    memory: 4096

network:
# WEB UI
  web_port:
    bind_mode: published
    port_number: 8081
# HTTP
  http_enable: true
  http_port:
    bind_mode: published
    port_number: 8080
# HTTPS
  https_enable: true
  https_port:
    bind_mode: published
    port_number: 8443
  additional_ports: []
#HTTPS Redirect
  https_redirect: false

ix_volumes:
  letsencrypt: /opt/tests/mnt/letsencrypt


storage:
#Docker Socket access
  enable_docker_socket: true
#Letsencrypt volume
  letsencrypt:
    type: ix_volume
    ix_volume_config:
      dataset_name: letsencrypt
      create_host_path: true

proxy:
  challenge: ""