annotations:
  min_scale_version: 25.04.2.3
app_version: 3.5.2
capabilities:
- description: Traefik is able to change file ownership arbitrarily
  name: CHOWN
- description: Traefik is able to bypass file permission checks
  name: DAC_OVERRIDE
- description: Traefik is able to bypass permission checks for file operations
  name: FOWNER
- description: Traefik is able to change group ID of processes
  name: SETGID
- description: Traefik is able to change user ID of processes
  name: SETUID
categories:
- networking
changelog_url: https://github.com/traefik/traefik/releases
date_added: '2025-09-04'
description: Traefik (pronounced traffic) is a modern HTTP(s) reverse proxy and load balancer that makes deploying microservices easy.
home: https://traefik.io/
host_mounts: []
icon: https://media.sys.truenas.net/apps/ix-app/icons/icon.webp
keywords:
- reverse
- traefik
- proxy
- reverse-proxy
lib_version: 2.1.50
lib_version_hash: 82f6bd4b66d71cc5456607ea1faed36d33faca43a0af1c6555704df4c2104460
maintainers:
- email: dev@ixsystems.com
  name: truenas
  url: https://www.truenas.com/
name: traefik
run_as_context:
- description: Traefik Manager runs as root user.
  gid: 0
  group_name: root
  uid: 0
  user_name: root
screenshots:
- https://doc.traefik.io/traefik/assets/img/getting-started/traefik-dashboard.png
sources:
- https://traefik.io/
- https://hub.docker.com/_/traefik
title: Traefik
train: beta
version: 0.0.1
