# Generate docker compose template
{% set tpl = ix_lib.base.render.Render(values) %}

# Create traefik container
# Get name from TrueNAS UI
# Get container image & tag from ix_values.yaml
{% set traefik = tpl.add_container(values.consts.traefik_container_name, "image") %}

# Add Commands
{% do traefik.set_command(COMMAND) %}

# Add conditional commands
{% if values. %}
  {% do traefik.set_command(COMMAND) %}
{% endif %}

# Add Ports
{% do traefik.add_port(values.network.web_port) %}


# Add Environment variables
{% do traefik.environment.add_env("ENV_Variable", values.#VARIABLE#) %}

# Add conditional environment variables
{% if values. %}
  {% do traefik.environment.add_env("ENV_Variable", values.#VARIABLE#) %}
{% endif %}

# Add user added environment variables
{% do traefik.environment.add_user_envs(values.traefik.additional_envs) %}

# Add Volumes
# Add folder for letsencrypt certs
{% do traefik.add_storage(values.consts.letsencrypt, values.storage.consume) %}
# Mount Docker Socket

# Add User added Volumes
{% for store in values.storage.additional_storage %}
  {% do traefik.add_storage(store.mount_path, store) %}
{% endfor %}

# Do something IDK all thje apps have it
{% do tpl.portals.add(values.network.web_port) %}
{% do tpl.notes.set_body(values.consts.notes_body) %}

{{ tpl.render() | tojson }}