# Generate docker compose template
{% set tpl = ix_lib.base.render.Render(values) %}

# Create traefik container
# Get name from TrueNAS UI
# Get container image & tag from ix_values.yaml
{% set traefik = tpl.add_container(values.consts.traefik_container_name, "image") %}

# Add Commands
{% do traefik.set_command(["--api.insecure", values.consts.commands.api.insecure]) %}
{% do traefik.set_command(["--providers.docker", values.consts.commands.providers.docker]) %}
{% do traefik.set_command(["--providers.docker.exposedbydefault", values.consts.commands.docker.exposed]) %}
{% do traefik.set_command([]) %}
{% do traefik.set_command([]) %}
{% do traefik.set_command([]) %}

# Add conditional commands
# EntryPoints
#Check if http proxying is enabled and add entrypoint when nessecary
{% if values.network.http_enable %}
  {% do traefik.set_command(["--entryPoints.web.address", values.network.http_port.port_number]) %}
{% endif %}
#Check if https proxying is enabled and add entrypoint when nessecary
{% if values.network.https_enable %}
  {% do traefik.set_command(["--entryPoints.websecure.address", values.network.https_port.port_number]) %}
{% endif %}
#Check if https redirection is enabled and add enable https redirection if it is
{% if values.network.https_redirect %}
  {% do traefik.set_command(["--entrypoints.web.http.redirections.entrypoint.to=websecure"]) %}
  {% do traefik.set_command(["--entrypoints.web.http.redirections.entrypoint.scheme=https"]) %}
  {% do traefik.set_command(["--entrypoints.web.http.redirections.entrypoint.permanent=true"]) %}
{% endif %}




# Add Ports
{% do traefik.add_port(values.network.web_port) %}

# Add conditional ports


#ENVIRONMENT VARIABLES DO NOT YET SEEM ESSENTIAL, NEED TO WORK ON LATER
# Add Environment variables
#{% do traefik.environment.add_env("ENV_Variable", values.#VARIABLE#) %}

# Add conditional environment variables
#{% if values. %}
#  {% do traefik.environment.add_env("ENV_Variable", values.#VARIABLE#) %}
#{% endif %}

# Add user added environment variables
#{% do traefik.environment.add_user_envs(values.traefik.additional_envs) %}

# Add Volumes
# Add folder for letsencrypt certs
{% do traefik.add_storage(values.consts.letsencrypt, values.storage.consume) %}
# Mount Docker Socket
{% do traefik.add_docker_socket(read_only=True) %}


# Add User added Volumes
{% for store in values.storage.additional_storage %}
  {% do traefik.add_storage(store.mount_path, store) %}
{% endfor %}

# Do something IDK all thje apps have it
{% do tpl.portals.add(values.network.web_port) %}
{% do tpl.notes.set_body(values.consts.notes_body) %}

{{ tpl.render() | tojson }}